# Oil prices lectures

Needed content:
* Oil prices can be seen as a supply shock (Video)
* What happens if we do nothing (inflation spiral)
* So what should we do? Simulator: Use the interest rate to stabilize inflation
* Why does this work? Theory from the books

# The simple Excel simulator
Javier has calibrated everything to deal with integers, here is how the excel looks like
![](2022-08-17-09-34-27.png)

In [34]:
%matplotlib inline
# Load dependencies
from pycel import ExcelCompiler
import pycel
import matplotlib.pyplot as plt
import os
import pandas as pd

filename = r'simple_simulator.xlsx'

In [41]:
#
# This needs to be serialized and loaded directly to avoid
# parsing of the excel every time the simulator is loaded 
# (Delete the .pkl file if you want to modify the excel)
#

# load & compile the file to a graph
excel = ExcelCompiler(filename=filename,cycles=True)

# We need to tell the excel compiler which cells we are interested in
supply_shock = excel.evaluate('simulator!J6')
inflation_sequence = excel.evaluate('simulator!A1:E30')

# Now we can save the graph to a pickle file
print("Serializing to disk...")
excel.to_file(filename + '.pkl')

Initialized with cycles: True, while workbook says: False

Serializing to disk...

In [42]:
# We can now display the parsed excel
display(supply_shock)
display(inflation_sequence)

-0.03

(('time', 'Yn', 'Y', 'Pi', 'Pi_e'),
 (1, 100, 100, 2, 2),
 (2, 100, 100, 2, 2),
 (3, 100, 100, 2, 2),
 (4, 100, 100, 2, 2),
 (5, 97, 100, 5, 2),
 (6, 97, 100, 8, 5),
 (7, 97, 100, 11, 8),
 (8, 97, 100, 14, 11),
 (9, 97, 100, 17, 14),
 (10, 97, 100, 20, 17),
 (11, 97, 100, 23, 20),
 (12, 97, 100, 26, 23),
 (13, 97, 100, 29, 26),
 (14, 97, 100, 32, 29),
 (15, 97, 100, 35, 32),
 (16, 97, 100, 38, 35),
 (17, 97, 100, 41, 38),
 (18, 97, 100, 44, 41),
 (19, 97, 100, 47, 44),
 (20, 97, 100, 50, 47),
 (21, 97, 100, 53, 50),
 (22, 97, 100, 56, 53),
 (23, 97, 100, 59, 56),
 (24, 97, 100, 62, 59),
 (25, 97, 100, 65, 62),
 (26, 97, 100, 68, 65),
 (27, 97, 100, 71, 68),
 (28, 97, 100, 74, 71),
 (29, 97, 100, 77, 74))

In [37]:
# Show it in a nice dataframe
pd.DataFrame(inflation_sequence[1:], columns=inflation_sequence[0])

    time   YN    Y   π  πe
0      1  100  100   2   2
1      2  100  100   2   2
2      3  100  100   2   2
3      4  100  100   2   2
4      5   98  100   4   2
5      6   98  100   6   4
6      7   98  100   8   6
7      8   98  100  10   8
8      9   98  100  12  10
9     10   98  100  14  12
10    11   98  100  16  14
11    12   98  100  18  16
12    13   98  100  20  18
13    14   98  100  22  20
14    15   98  100  24  22
15    16   98  100  26  24
16    17   98  100  28  26
17    18   98  100  30  28
18    19   98  100  32  30
19    20   98  100  34  32
20    21   98  100  36  34
21    22   98  100  38  36
22    23   98  100  40  38
23    24   98  100  42  40
24    25   98  100  44  42
25    26   98  100  46  44
26    27   98  100  48  46
27    28   98  100  50  48
28    29   98  100  52  50

# Simulator

In [45]:
# for some reason we need to reload the compiler
excel = ExcelCompiler.from_file(filename + '.pkl')

# Change the shock size parameter and reevaluate the excel
excel.set_value('simulator!J6', -0.04) # Change to -8%
display(excel.evaluate('simulator!J6'))
inflation_sequence = excel.evaluate('simulator!A1:E30')

# Show new results in a nice dataframe
pd.DataFrame(inflation_sequence[1:], columns=inflation_sequence[0])

-0.04

    time     Yn    Y   Pi  Pi_e
0      1  100.0  100    2     2
1      2  100.0  100    2     2
2      3  100.0  100    2     2
3      4  100.0  100    2     2
4      5   96.0  100    6     2
5      6   96.0  100   10     6
6      7   96.0  100   14    10
7      8   96.0  100   18    14
8      9   96.0  100   22    18
9     10   96.0  100   26    22
10    11   96.0  100   30    26
11    12   96.0  100   34    30
12    13   96.0  100   38    34
13    14   96.0  100   42    38
14    15   96.0  100   46    42
15    16   96.0  100   50    46
16    17   96.0  100   54    50
17    18   96.0  100   58    54
18    19   96.0  100   62    58
19    20   96.0  100   66    62
20    21   96.0  100   70    66
21    22   96.0  100   74    70
22    23   96.0  100   78    74
23    24   96.0  100   82    78
24    25   96.0  100   86    82
25    26   96.0  100   90    86
26    27   96.0  100   94    90
27    28   96.0  100   98    94
28    29   96.0  100  102    98